### ISSUE TITLE
Failed at npm start

### ISSUE THREAD

**Issue by cichy** [TriPSs/react-esc-example#11]
`ERROR in ./src/styles/assets/Duck.jpg
Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/admin/Git/react-esc-example/node_modules/mozjpeg/vendor/cjpeg
  Reason: image not found

    at Promise.all.then.arr (/Users/admin/Git/react-esc-example/node_modules/execa/index.js:201:11)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
 @ ./src/routes/Home/HomeComponent.js 16:12-45
 @ ./src/routes/Home/index.js
 @ ./src/layouts/CoreLayout/CoreLayout.js
 @ ./src/routes/index.js
 @ ./~/react-esc/client/client.js
 @ ./~/react-esc/client/index.js
 @ ./src/client.js
 @ multi ./src/client.js webpack-hot-middleware/client?path=http://192.168.0.13:3000/__webpack_hmr`

**Comment by TriPSs** [comment]
@cichy Did you check the readme?

![image](https://cloud.githubusercontent.com/assets/7668692/24588699/e94d77f6-17cd-11e7-953a-5fd74418f6e8.png)

**Comment by TriPSs** [comment]
Plz reopen if you still have problems.
