### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by kuatro** [TriPSs/react-esc-example#13]
Hi. I noticed that since you migrated to `react-router` v4 this app lost the ability to split routes to separated bundle files. Please, correct me if I just misunderstood something.

**Comment by TriPSs** [comment]
This is correct! If I remember correctly react router v4 does not support this any more. 

If you still want to have code splitting you can use V1 of `react-ecs` that still uses react router v3. 

Or if I'm wrong and react router v4 is supporting this could you then please provide a link., then i will look into it.

**Comment by kuatro** [comment]
I found a third-party [package](https://github.com/zackify/react-router-async-routing) for this. But I'm not sure if it's 100% fits to our stack.

**Comment by TriPSs** [comment]
Hmm, i don't think it's a good fit this project! When react router supports it again i will update the project.
